# create your drupal and postgres config here, based off the last assignment

# create secret:
  # echo "secretpass" | docker secret create psql-pw -

    # run
    # docker stack deploy -c docker-compose.yml secret_test

version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports: 
      - 8080:80
    environment:
        POSTGRES_DB: drupal
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass 
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postges:
    image: postgres:9.6
    environment: 
        POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
    volumes: 
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - psql-pw

volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    drupal-data:

secrets:
    psql-pw: 
      external: true